export const betConfig = [
    {
        gain: 36,
        gridCol: "1",
        gridRow: "1/4",
        id: 0,
        title: "0",
        value: 0,
        background: "green",
        condition: (val) => val > 0 && val < 13,
    },
    {
        id: 35,
        title: "1st 12",
        value: 0,
        gain: 3,
        gridCol: "2 / 6",
        back: "green",
        condition: (val) => val > 0 && val < 13,
    },
    {
        id: 36,
        title: "2nd 12",
        value: 0,
        gain: 3,
        gridCol: "6/10",
        back: "green",
        condition: (val) => val > 12 && val < 25,
    },
    {
        id: 37,
        title: "3rd 12",
        value: 0,
        gain: 3,
        gridCol: "10/14",
        back: "green",
        condition: (val) => val > 24,
    },
    {
        id: 38,
        title: "1 To 18",
        value: 0,
        gain: 2,
        gridCol: "2/4",
        back: "green",
        condition: (val) => val > 0 && val < 18,
    },
    {
        id: 39,
        title: "EVEN",
        value: 0,
        gain: 2,
        gridCol: "4/6",
        back: "green",
        condition: (val) => val % 2 === 0,
    },
    {
        id: 40,
        title: "R",
        value: 0,
        gain: 2,
        gridCol: "6/8",
        back: "red",
        condition: (val) => red_number.includes(val),
    },
    {
        id: 41,
        title: "B",
        value: 0,
        gain: 2,
        gridCol: "8/10",
        back: "black",
        condition: (val) => !red_number.includes(val),
    },
    {
        id: 42,
        title: "ODD",
        value: 0,
        gain: 2,
        gridCol: "10/12",
        back: "green",
        condition: (val) => val % 2 === 1,
    },
    {
        id: 43,
        title: "19 To 36",
        value: 0,
        gain: 2,
        gridCol: "12/14",
        back: "green",
        condition: (val) => val >= 19,
    },
    {
        id: 44,
        title: "2to1",
        value: 0,
        gain: 3,
        gridCol: "14",
        gridRow: "1",
        back: "green",
        condition: (val) => val % 3 === 0,
    },
    {
        id: 45,
        title: "2to1",
        value: 0,
        gain: 3,
        gridCol: "14",
        gridRow: "2",
        back: "green",
        condition: (val) => (val + 1) % 3 === 0,
    },
    {
        id: 46,
        title: "2to1",
        value: 0,
        gain: 3,
        gridCol: "14",
        gridRow: "3",
        back: "green",
        condition: (val) => (val + 2) % 3 === 0,
    },
];
